FormKey: 00090B:Portable Junk Recycler Mk 2.esp
VersionControl: 11065
EditorID: PJRM2_Message_SettingsResetFailRunning
Description:
  TargetLanguage: English
  Value: >-
    <font size='24'><b><u>Portable Junk Recycler Mk 2</u></b></font>


    Could not reset settings to defaults because there's a recycling process currently running.
Flags:
- MessageBox
